language: cpp
os: windows
cache:
  directories:
    - $HOME/.conan/
    - C:/.conan
install:
  - choco install conan -y -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
  - choco install ninja visualstudio2019buildtools visualstudio2019-workload-vctools -y
script:
  - export CXX="cl.exe"
  - export CXX_FOR_BUILD="cl.exe"
  - export CC="cl.exe"
  - export CC_FOR_BUILD="cl.exe"
  - ./.ci/run.bat