dist: bionic
language: cpp

cache:
  directories:
    - $HOME/.conan/

matrix:
  include:
    - os: linux
      name: Linux Build
      install:
        - wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_24_1.deb -nv
        - sudo dpkg -i ./conan-ubuntu-64_1_24_1.deb
        - conan user
      script:
        - cmake .
        - cmake --build .

    - os: windows
      name: Windows Build
      install:
        - choco install conan -y -s="https://api.bintray.com/nuget/anotherfoxguy/choco-pkg"
      script:
        - cmd.exe //c "RefreshEnv.cmd & cmake ."
        - cmake --build .